### ISSUE TITLE
Use SLF4J

### ISSUE THREAD

**Issue by austinv11** [api-ai/apiai-java-client#14]
SLF4J is a much better logging standard than log4j as it is both faster and more easily configurable for the end user. I would urge you to take a look at it. They also provide a bridge for using log4j so you may keep using that if its more comfortable for you.

https://www.slf4j.org/

**Comment by folomeev** [comment]
Thank you! We will consider the possibility of adding support for this library in one of the following versions.

**Comment by folomeev** [comment]
Replaced log4j with slf4j.
Will be available in upcoming version.
