### ISSUE TITLE
Update Log4j version, improve tests

### ISSUE THREAD

**Issue by ryantgraham** [api-ai/apiai-java-client#16]
Hello,
A handful of requests:
1. Update the Log4j version to 2.4 (or later) so that the library works on the Google App Engine, https://issues.apache.org/jira/browse/LOG4J2-1035
2. There are some tests in `AIResponseTest` and `ParametersConverterTest` that are failing due to what appears to be timezone issues
3. The _libai-speech-gcp_ goal is failing.

I'd be happy to open a PR to address items 1 and 2. Item 3 would require some additional investigation.

Thanks!

**Comment by folomeev** [comment]
- Removed log4j support, used slf4j instead
- Test failures fixed
