### ISSUE TITLE
Tests parsePartialDateTest fails on libai build

### ISSUE THREAD

**Issue by gabouy** [api-ai/apiai-java-client#18]
Hi,

My env is Ubuntu 16.04, with jvm/java-7-openjdk-amd64

I did:
1. git clone
2. mvn package

Build fails with failed tests:   

parsePartialDateTest(ai.api.util.ParametersConverterTest): expected:<5> but was:<6>
  testCustomContext(ai.api.AIDataServiceTest): null expected:<[Europe/London]> but was:<[GMT]>

If I skip tests, then javadoc fails, if I skip that, then libai-speech-gcp  fails.

Why I feel I'm missing a step here?

Any help or clarification would be much appreciated,

thanks

**Comment by folomeev** [comment]
Hello, 

would you be so kind to pull `master` branch and re-run:

```mvn package```

Thanks

**Comment by folomeev** [comment]
I guess fixed.
