### ISSUE TITLE
Doesn't work for Google Assistant

### ISSUE THREAD

**Issue by wiradikusuma** [api-ai/apiai-java-client#19]
This is the JSON returned by Node.js client:

    {
        "speech": "Sure, here's a history fact. Google was founded by Larry Page and Sergey Brin. Would you like to hear another fact?",
        "contextOut": [
            {
                "name": "_actions_on_google_",
                "lifespan": 100,
                "parameters": {
                    "historyFacts": [
                        "Google went public in 2004.",
                        "Google has more than 70 offices in more than 40 countries."
                    ]
                }
            }
        ],
        "data": {
            "google": {
                "expect_user_response": true,
                "is_ssml": false,
                "no_input_prompts": [
                    {
                        "text_to_speech": "I didn't hear that."
                    },
                    {
                        "text_to_speech": "If you're still there, say that again."
                    },
                    {
                        "text_to_speech": "We can stop here. See you soon."
                    }
                ]
            }
        }
    }

This is the JSON returned by Java client:

    {
        "speech": "Meh"
    }

As you can expect, api.ai is not happy:

    "status": {
        "code": 206,
        "errorType": "partial_content",
        "errorDetails": "Webhook call failed. Error: Webhook response was empty."
    }

**Comment by wiradikusuma** [comment]
Actually, it might be due to wrong content type: https://github.com/api-ai/apiai-java-client/pull/20

**Comment by gubs4u** [comment]
I almost spend a day breaking my head to figure out this issue. I also got the same 206 error and upon AIWebhookServlet.RESPONSE_CONTENT_TYPE String value changed from 'Content-Type: application/json' to 'application/json' it worked.

**Comment by wiradikusuma** [comment]
Already merged.
