### ISSUE TITLE
Not able to build the code getting error Could not find artifact io.netty

### ISSUE THREAD

**Issue by rahulsharma29** [api-ai/apiai-java-client#23]
[ERROR] Failed to execute goal on project voice-client: Could not resolve depend
encies for project ai.api.libai.examples:voice-client:jar:1.4.8: Could not find
artifact io.netty:netty-tcnative-boringssl-static:jar:${os.detected.classifier}:
1.1.33.Fork25 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by folomeev** [comment]
Please try to pull latest code from `master` branch and try again.

**Comment by rahulsharma29** [comment]
What is the path of master branch?

**Comment by folomeev** [comment]
Please try this commands to clone and install `master` branch code into your local machine 
```bash
git clone https://github.com/api-ai/apiai-java-client.git && \
	cd apiai-java-client && \
	mvn install && \
	cd samples/clients && \
	mvn package
```

**Comment by folomeev** [comment]
I guess fixed.
