### ISSUE TITLE
simple_response fulfillment message type unsupported in API when i fill the default response on intent creation

### ISSUE THREAD

**Issue by gubs4u** [api-ai/apiai-java-client#25]
I followed the same example of yahoo-weather and based on the same only i put the default response assuming on failure of webhook response the default response will pop up.  But, i am getting error simple_response fulfillment message type unsupported in API

https://github.com/api-ai/apiai-java-client/blob/master/web/servlet/src/main/java/ai/api/web/AIWebhookServlet.java and i am using same 

AIWebhookServlet.java in my code to receive the data and parse. Exactly in the 
    doWebhook(gson.fromJson(request.getReader(), AIWebhookRequest.class), output); its failing in case of default response if i add. If i remove the default response then response from server comes but, if the server failed to respond then default error response is not poping up.

thanks,
gubs

**Comment by folomeev** [comment]
Committed initial support into `master` branch. You may try to assembly the latest version of the library and check again.

**Comment by gubs4u** [comment]
Thanks @folomeev . I took libai code from master and everything working fine as expected. 

I had given TextResponse along with webhook fulfillment and the response comes webhook properly without error. Also, when the webhook server down, i get proper response from TextResponse.
