### ISSUE TITLE
MessageType deserialization issue

### ISSUE THREAD

**Issue by arsenalol1** [api-ai/apiai-java-client#30]
Hi ! 

I encoutred a problem with deserialization of the attribute ResponseMessage.type . When I deserialize a Json like this one : 
`"fulfillment": {
      "speech": "Howdy.",
      "messages": [
        {
          "type": 0,
          "speech": "Howdy."
        }
      ]
    },`
the attribute 'type' of ResponseMessage.ResponseSpeech is null.
Here is my code : 
`ResponseSpeech re = (ResponseSpeech)GsonFactory.getDefaultFactory().getGson().fromJson("{ \"speech\": \"Hey!\",\"messages\": [{\"type\": 0,\"speech\": \"Howdy.\" }]}", Fulfillment.class).getMessages().get(0);`

Thanks !

**Comment by folomeev** [comment]
The field `ResponseMessage.type` is private and not supposed to be used outside of the class.

How do you use it?

**Comment by arsenalol1** [comment]
I checked the value with the debugger ^^.
